export const AD_SLOT_STATUSES = ["winning", "nofill"] as const;
export type AdSlotStatus = (typeof AD_SLOT_STATUSES)[number];

export type AdSlot = {
  id: string;
  name: string;
  size: string; // "300x250, "728x90", etc. format IAB standard
  status: AdSlotStatus;
  revenue: number; // revenue generated by this ad slot 0 in case of no-fill
}

export const mockAdSlots: AdSlot[] = [
  { id: "slot-1", name: "Leaderboard", size: "728x90", status: "winning", revenue: 12.34 },
  { id: "slot-2", name: "Medium Rectangle", size: "300x250", status: "nofill", revenue: 0 },
  { id: "slot-3", name: "Large Rectangle", size: "336x280", status: "winning", revenue: 8.56 },
  { id: "slot-4", name: "Skyscraper", size: "160x600", status: "winning", revenue: 5.67 }
];
